// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdyaYeNQwcI9LJy9zGOtgStjbqMvkQg1g',
    appId: '1:813764091196:web:cc71a157cb5a6c56001239',
    messagingSenderId: '813764091196',
    projectId: 'nomad-one',
    authDomain: 'nomad-one.firebaseapp.com',
    storageBucket: 'nomad-one.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mvF81XYND8L3EFgGOdn7bpl-ip2iKA0',
    appId: '1:813764091196:android:19f9591726f0a4fe001239',
    messagingSenderId: '813764091196',
    projectId: 'nomad-one',
    storageBucket: 'nomad-one.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk31R7HLRBqeDGAEaHUDWFOMLS9rxdgCM',
    appId: '1:813764091196:ios:b73d13db3e61b92d001239',
    messagingSenderId: '813764091196',
    projectId: 'nomad-one',
    storageBucket: 'nomad-one.appspot.com',
    iosClientId: '813764091196-cert74427kmv593764j3jq873c9qkq0u.apps.googleusercontent.com',
    iosBundleId: 'com.nomad.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk31R7HLRBqeDGAEaHUDWFOMLS9rxdgCM',
    appId: '1:813764091196:ios:b73d13db3e61b92d001239',
    messagingSenderId: '813764091196',
    projectId: 'nomad-one',
    storageBucket: 'nomad-one.appspot.com',
    iosClientId: '813764091196-cert74427kmv593764j3jq873c9qkq0u.apps.googleusercontent.com',
    iosBundleId: 'com.nomad.myPortfolio',
  );
}
